### PR TITLE
Fix: Update Total Parameter for layer add and delete(#126)

### LINKED ISSUE #126: Display parameters of the model being visualized
We should display the number of parameters(weights of the model) the model contains somewhere on the screen. These parameter values should change whenever a new layer is added or some existing layer is changed.

### PR DESCRIPTION
**Pull request by Ram81**
@utsavgarg Fixes #126

### CODE REVIEW

**Comment by utsavgarg** [comment]
@Ram81 this looks good but the calculation doesn't seem to be working when adding a new layer, this might be because it's not connected when added and the input and output shapes are not defined. We might need to trigger the calculation when the parameter values are changed rather than when a layer is added.

**Comment by Ram81** [comment]
@utsavgarg Yeah I also noticed that, do you want me to add the logic for modification of parameters and connection establishment updates in same PR ?
Because I thought you would want that handled separately for a new connection addition & modification of parameters, as new connection could be added in between too i.e. non-leaf nodes of graph.

**Comment by utsavgarg** [comment]
@Ram81 Nice effort :) It's definitely an improvement from before, but I still see some issues with the calculation
ezgif com-video-to-gif

File: ide/static/js/content.js [hunk 1]
```diff
@@ -92,8 +93,28 @@ class Content extends React.Component {
...
+    net[layerId] = layer;
+    // Parsing for integer parameters when new layers are added as by default all params are string
+    var intParams = ["crop_size", "num_output", "new_height", "new_width", "height", "width", "kernel_h", "kernel_w",
+                      "kernel_d", "stride_h", "stride_w", "stride_d", "pad_h", "pad_w", "pad_d", "size_h", "size_w",
+                      "size_d", "n"];
+    Object.keys(net[layerId].params).forEach(param => {
+      if (intParams.includes(param)){
+        net[layerId].params[param][0] = parseInt(net[layerId].params[param][0]);
+        if (isNaN(net[layerId].params[param][0]))
+          net[layerId].params[param][0] = parseInt(0);
```
Comment (utsavgarg) [inline ide/static/js/content.js]: is a `parseInt` necessary here?

File: ide/static/js/content.js [hunk 2]
```diff
@@ -92,8 +93,28 @@ class Content extends React.Component {
   }
   addNewLayer(layer) {
     const net = this.state.net;
-    net[`l${this.state.nextLayerId}`] = layer;
-    this.setState({ net, nextLayerId: this.state.nextLayerId + 1 });
+    const layerId = `l${this.state.nextLayerId}`;
+    var totalParameters = this.state.totalParameters;
+    net[layerId] = layer;
+    // Parsing for integer parameters when new layers are added as by default all params are string
```
Comment (utsavgarg) [inline ide/static/js/content.js]: Also add a comment that some parameters might have been missed, or are you sure you've covered all?

File: ide/static/js/content.js [hunk 3]
```diff
@@ -92,8 +93,28 @@ class Content extends React.Component {
...
+                      "kernel_d", "stride_h", "stride_w", "stride_d", "pad_h", "pad_w", "pad_d", "size_h", "size_w",
+                      "size_d", "n"];
+    Object.keys(net[layerId].params).forEach(param => {
+      if (intParams.includes(param)){
+        net[layerId].params[param][0] = parseInt(net[layerId].params[param][0]);
+        if (isNaN(net[layerId].params[param][0]))
+          net[layerId].params[param][0] = parseInt(0);
+      }
+    });
+    //console.log(layer);
```
Comment (utsavgarg) [inline ide/static/js/content.js]: Remove

File: ide/static/js/content.js [hunk 4]
```diff
@@ -92,8 +93,28 @@ class Content extends React.Component {
...
+    this.updateLayerShape(net, layerId);
+    // Check for only layers with valid shape
+    if (net[layerId]['shape']['input'] != null && net[layerId]['shape']['output'] != null) {
+      net[layerId]['shape']['parameters'] = this.getLayerParameters(net[layerId], net);
```
Comment (utsavgarg) [inline ide/static/js/content.js]: It's probably better to store this in `info` rather than `shape`

File: ide/static/js/content.js [hunk 5]
```diff
@@ -122,8 +143,16 @@ class Content extends React.Component {
 
   modifyLayer(layer, layerId = this.state.selectedLayer) {
     const net = this.state.net;
+    var oldLayerParams = this.state.totalParameters;
```
Comment (utsavgarg) [inline ide/static/js/content.js]: Instead of repeating this portion of the code from `modifyLayerParams` can we have a separate function which has this in one place and both these functions can call it.

File: ide/static/js/content.js [hunk 6]
```diff
@@ -202,11 +233,43 @@ class Content extends React.Component {
...
+      url: 'layer_parameter/',
+      dataType: 'json',
+      type: 'POST',
+      async: false,
+      data: {
+        net: JSON.stringify(netData),
+        layerId: layerId
+      },
+      success : function (response) {
+        //this.setState({ net: response.net, nextLayerId: this.state.nextLayerId + 1 });
```
Comment (utsavgarg) [inline ide/static/js/content.js]: Remove

File: ide/static/js/setParams.js [hunk 7]
```diff
@@ -22,10 +22,19 @@ class SetParams extends React.Component {
     const net = this.props.net;
     let layer = net[this.props.selectedLayer];
     layer = JSON.parse(JSON.stringify(layer));
+    var intParams = ["crop_size", "num_output", "new_height", "new_width", "height", "width", "kernel_h", "kernel_w",
```
Comment (utsavgarg) [inline ide/static/js/setParams.js]: Do we need to parse these as `int` at two places?

Comment (Ram81) [reply ide/static/js/setParams.js]: Yeah because when layer is added it doesn't use setparams

File: ide/static/js/content.js (hunk 5 above)
Comment (Ram81) [reply ide/static/js/content.js]: I modified old logic where we have to update layer after param pane is closed which does exactly the same thing you are asking for, now we don't call modifyLayer from modifyLayerParams
